name: Documentation Improvement
description: Suggest improvements to CrowdUp documentation
title: "[DOCS]: "
labels: ["Documentation 📚"]
projects: ["CrowdUp-org/4"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve the CrowdUp documentation!

  - type: input
    id: doc-link
    attributes:
      label: Documentation Link
      description: Link to the documentation page that needs improvement (if applicable)
      placeholder: "https://docs.crowdup.com/page"
    validations:
      required: false

  - type: dropdown
    id: improvement-type
    attributes:
      label: Type of Improvement
      description: What kind of documentation improvement are you suggesting?
      options:
        - Error Correction
        - Clarification Needed
        - Missing Information
        - Outdated Content
        - New Documentation Needed
        - Formatting/Structure Issue
        - Other
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current state of the documentation
      placeholder: "The current documentation says..."
    validations:
      required: true

  - type: textarea
    id: suggested-change
    attributes:
      label: Suggested Change
      description: Describe your suggested improvement
      placeholder: "The documentation should be updated to..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation improvement
      placeholder: "More details that might help understand the suggestion better."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this documentation improvement yourself?
      options:
        - label: I am willing to submit a PR with these changes
          required: false
