name: Feature Request
description: Suggest a new feature for CrowdUp
title: "[FEATURE]: "
labels: ["Feature Request 🚀"]
type: Improvement
projects: ["CrowdUp-org/4"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for CrowdUp!

        NOTE: If you're proposing an improvement to an existing feature (performance, UX polish, refactor, optimization, incremental enhancement), please use the "Enhancement" template instead. Use this "Feature Request" template for new capabilities or functionality that doesn't exist yet.
        
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: "I would like to see..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Other approaches that might work could be..."
    validations:
      required: false
      
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "More details that might help understand the request better."
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature yourself?
      options:
        - label: I am willing to submit a PR for this feature
          required: false